languages = {
    "中文": {
        "title": "OpenAI TTS Web",
        "intro": "这是一个由[MaktubCN](https://github.com/MaktubCN)构建的简单[OpenAI TTS Web](https://github.com/MaktubCN/OpenAI-TTS-WebUI)，欢迎大家使用👏",
        "input_text_label": "输入文本",
        "input_text_placeholder": "请输入要合成的文本",
        "model_label":"模型",
        "voice_label": "声音",
        "output_format_label": "输出格式",
        "generate_button_label": "生成",
        "output_audio_label": "输出音频",
        "settings_label": "设置",
        "base_url_label": "Base URL",
        "api_key_label": "API Key",
        "interface_mode_label": "界面模式",
        "theme_label": "主题",
        "language_label": "界面语言",
        "light_mode": "明亮模式",
        "dark_mode": "黑暗模式",
        "history_label": "历史文件",
        "delete_button_label": "清除所有历史文件",
        "delete_file_button": "删除",
        "BOW":"切换黑白主题",
    },
    "English": {
        "title": "OpenAI TTS Web",
        "intro": "This is a simple [OpenAI TTS Web](https://github.com/MaktubCN/OpenAI-TTS-WebUI) built by [MaktubCN](https://github.com/MaktubCN), you are welcome to use it 👏!",
        "input_text_label": "Input Text",
        "input_text_placeholder": "Please enter the text to synthesize",
        "model_label":"model",
        "voice_label": "Voice",
        "output_format_label": "Output Format",
        "generate_button_label": "Generate",
        "output_audio_label": "Output Audio",
        "settings_label": "Settings",
        "base_url_label": "Base URL",
        "api_key_label": "API Key",
        "interface_mode_label": "Interface Mode",
        "theme_label": "Theme",
        "language_label": "Language",
        "light_mode": "Light Mode",
        "dark_mode": "Dark Mode",
        "history_label": "History Files",
        "delete_button_label": "Clear All History Files",
        "delete_file_button": "Delete",
        "BOW": "Switch Theme",
    }
}
